services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wasel
    ports:
      - "5432:5432"

  backend:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    env_file:
      - .env